version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY}/portfolio-backend:${BUILD_NUMBER}
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=4000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - portfolio_logs:/app/logs
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  frontend:
    image: ${DOCKER_REGISTRY}/portfolio-frontend:${BUILD_NUMBER}
    restart: always
    networks:
      - portfolio-network
    depends_on:
      - backend

  # Nginx reverse proxy for routing and SSL termination
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network

volumes:
  portfolio_logs:

networks:
  portfolio-network:
    driver: bridge
